           SET MOD-IDX TO 1
           SET WS-MOD-POINTER(MOD-IDX) TO ENTRY 'DTEXTHOOK'
           SET WS-MOD-BODY(MOD-IDX)    TO "B: "
           SET WS-MOD-COLOR-FG(MOD-IDX)   TO "ff0f0fff"
           SET WS-MOD-COLOR-BG(MOD-IDX)   TO "00000000"
           SET MOD-IDX TO 2
           SET WS-MOD-POINTER(MOD-IDX) TO ENTRY 'DSPACEHOOK'
           SET WS-MOD-BODY(MOD-IDX)    TO SPACES
           SET WS-MOD-COLOR-FG(MOD-IDX)   TO "ff0f0fff"
           SET WS-MOD-COLOR-BG(MOD-IDX)   TO "00000000"
           SET MOD-IDX TO 3
           SET WS-MOD-POINTER(MOD-IDX) TO ENTRY 'DBATTHOOK'
           SET WS-MOD-BODY(MOD-IDX)    TO "CAPACITY"
           SET WS-MOD-COLOR-FG(MOD-IDX)   TO "ff0f0fff"
           SET WS-MOD-COLOR-BG(MOD-IDX)   TO "000000ff"
           SET MOD-IDX TO 4
           SET WS-MOD-POINTER(MOD-IDX) TO ENTRY 'DSEPHOOK'
           SET WS-MOD-BODY(MOD-IDX)    TO "-"
           SET WS-MOD-COLOR-FG(MOD-IDX)   TO "ff0f0fff"
           SET WS-MOD-COLOR-BG(MOD-IDX)   TO "00000000"
           SET MOD-IDX TO 5
           SET WS-MOD-POINTER(MOD-IDX) TO ENTRY 'DTEXTHOOK'
           SET WS-MOD-BODY(MOD-IDX)    TO "U: "
           SET WS-MOD-COLOR-FG(MOD-IDX)   TO "ffffffff"
           SET WS-MOD-COLOR-BG(MOD-IDX)   TO "00000000"
           SET MOD-IDX TO 6
           SET WS-MOD-POINTER(MOD-IDX) TO ENTRY 'DSPACEHOOK'
           SET WS-MOD-BODY(MOD-IDX)    TO SPACES
           SET WS-MOD-COLOR-FG(MOD-IDX)   TO "ff0f0fff"
           SET WS-MOD-COLOR-BG(MOD-IDX)   TO "00000000"
           SET MOD-IDX TO 7
           SET WS-MOD-POINTER(MOD-IDX) TO ENTRY 'DMEMHOOK'
           SET WS-MOD-BODY(MOD-IDX)    TO "USED"
           SET WS-MOD-COLOR-FG(MOD-IDX)   TO "ffffffff"
           SET WS-MOD-COLOR-BG(MOD-IDX)   TO "00000000"
           SET MOD-IDX TO 8
           SET WS-MOD-POINTER(MOD-IDX) TO ENTRY 'DSPACEHOOK'
           SET WS-MOD-BODY(MOD-IDX)    TO SPACES
           SET WS-MOD-COLOR-FG(MOD-IDX)   TO "ff0f0fff"
           SET WS-MOD-COLOR-BG(MOD-IDX)   TO "00000000"
           SET MOD-IDX TO 9
           SET WS-MOD-POINTER(MOD-IDX) TO ENTRY 'DTEXTHOOK'
           SET WS-MOD-BODY(MOD-IDX)    TO "A: "
           SET WS-MOD-COLOR-FG(MOD-IDX)   TO "ffffffff"
           SET WS-MOD-COLOR-BG(MOD-IDX)   TO "00000000"
           SET MOD-IDX TO 10
           SET WS-MOD-POINTER(MOD-IDX) TO ENTRY 'DSPACEHOOK'
           SET WS-MOD-BODY(MOD-IDX)    TO SPACES
           SET WS-MOD-COLOR-FG(MOD-IDX)   TO "ff0f0fff"
           SET WS-MOD-COLOR-BG(MOD-IDX)   TO "00000000"
           SET MOD-IDX TO 11
           SET WS-MOD-POINTER(MOD-IDX) TO ENTRY 'DMEMHOOK'
           SET WS-MOD-BODY(MOD-IDX)    TO "AVAILABLE"
           SET WS-MOD-COLOR-FG(MOD-IDX)   TO "ffffffff"
           SET WS-MOD-COLOR-BG(MOD-IDX)   TO "00000000"
           SET MOD-IDX TO 12
           SET WS-MOD-POINTER(MOD-IDX) TO ENTRY 'DSEPHOOK'
           SET WS-MOD-BODY(MOD-IDX)    TO "-"
           SET WS-MOD-COLOR-FG(MOD-IDX)   TO "ff0f0fff"
           SET WS-MOD-COLOR-BG(MOD-IDX)   TO "00000000"
           SET MOD-IDX TO 13
           SET WS-MOD-POINTER(MOD-IDX) TO ENTRY 'DLOADHOOK'
           SET WS-MOD-BODY(MOD-IDX)    TO SPACES
           SET WS-MOD-COLOR-FG(MOD-IDX)   TO "ff0fffff"
           SET WS-MOD-COLOR-BG(MOD-IDX)   TO "00000000"
           SET MOD-IDX TO 14
           SET WS-MOD-POINTER(MOD-IDX) TO ENTRY 'DSEPHOOK'
           SET WS-MOD-BODY(MOD-IDX)    TO "-"
           SET WS-MOD-COLOR-FG(MOD-IDX)   TO "ff0f0fff"
           SET WS-MOD-COLOR-BG(MOD-IDX)   TO "00000000"
           SET MOD-IDX TO 15
           SET WS-MOD-POINTER(MOD-IDX) TO ENTRY 'DDATEHOOK'
           SET WS-MOD-BODY(MOD-IDX)    TO "Y2.1K"
           SET WS-MOD-COLOR-FG(MOD-IDX)   TO "ffffffff"
           SET WS-MOD-COLOR-BG(MOD-IDX)   TO "00000000"
           SET MOD-IDX TO 16
           SET WS-MOD-POINTER(MOD-IDX) TO ENTRY 'DSEPHOOK'
           SET WS-MOD-BODY(MOD-IDX)    TO "-"
           SET WS-MOD-COLOR-FG(MOD-IDX)   TO "ff0f0fff"
           SET WS-MOD-COLOR-BG(MOD-IDX)   TO "00000000"
           SET MOD-IDX TO 17
           SET WS-MOD-POINTER(MOD-IDX) TO ENTRY 'DTIMEHOOK'
           SET WS-MOD-BODY(MOD-IDX)    TO "24H"
           SET WS-MOD-COLOR-FG(MOD-IDX)   TO "ffff0fff".
           SET WS-MOD-COLOR-BG(MOD-IDX)   TO "00000000"
           SET WS-MODULES-LOADED       TO 17
